# Generated by Django 5.1.1 on 2024-10-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0002_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otp",
            name="user",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name="Users",
        ),
    ]
