# Generated by Django 5.1.1 on 2024-10-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0003_alter_otp_user_delete_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="Upload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine_name", models.CharField(max_length=100)),
                ("medicine_image", models.ImageField(upload_to="images/")),
                ("medicine_price", models.FloatField()),
                ("medicine_description", models.TextField()),
            ],
        ),
    ]
