# Generated by Django 5.1.1 on 2024-10-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0004_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="upload",
            name="medicine_image",
            field=models.ImageField(upload_to="static/images/"),
        ),
    ]
